In [7]:
import pandas as pd
df = pd.read_csv('data/grid-puzzles-ordered-new.csv')
df.shape

(642, 7)

In [8]:
df.head().T

,0,1,2,3,4
Grid,3x4,3x4,3x4,3x4,3x4
Difficulty,Easy,Easy,Easy,Easy,Easy
Story,The Abbeville K-9 Academy trains dogs for use ...,The Maplewood Canine Training Center prepares ...,"The Byronville Gaming Club holds one ""game nig...","The Maplewood Puzzle Society hosts a monthly ""...",Mayor Price has promised to get the streets of...
Clues,1.The canine that graduated in May was either ...,1.The animal that finished training in June wa...,1.The board game played in January was hosted ...,1.The puzzle game played in March was hosted b...,1.The four projects are the job starting in Ju...
Table,+----------+--------+------------+\n| Months ...,NaN,+----------+---------+---------+\n| Months |...,NaN,+----------+-----------+-----------+\n| Months...
Options,"Dogs: Aries, Barca, Hercules, Jaws\nOfficers: ...",NaN,"Games: Android Disco, Planets Align, Rules of ...",NaN,"Streets: Ivy Street, Juniper Lane, Russell Roa..."
Puzzle,\nStory:\nThe Abbeville K-9 Academy trains dog...,Story:\nThe Maplewood Canine Training Center p...,\nStory:\nThe Byronville Gaming Club holds one...,Story:\nThe Maplewood Puzzle Society hosts a m...,\nStory:\nMayor Price has promised to get the ...

In [10]:
df.tail(n=1).T

                                                          641
Grid                                                      3x5
Difficulty                                        Challenging
Story       In a remote part of the Amazon rainforest, a w...
Clues       1.The 5-year-old is either the animal Lila wor...
Table                                                     NaN
Options                                                   NaN
Puzzle      Story:\nIn a remote part of the Amazon rainfor...

In [15]:
df.iloc[641]['Puzzle']

'Story:\nIn a remote part of the Amazon rainforest, a wildlife conservationist named Clara has established a small tamarin sanctuary where injured and orphaned tamarins are rehabilitated and eventually released back into their natural habitat. Using only the clues below, match each tamarin at the sanctuary with its age and caretaker, and determine where each animal was originally found. Remember, as with all grid-based logic puzzles, no option in any category will ever be used more than once. If you get stuck or run into problems, try the "Clear Errors" button to remove any mistakes that might be present on the grid, or the "Hint" button to see the next logical step in the puzzle.\n\nClues:\n1.The 5-year-old is either the animal Lila works with or the tamarin Mika works with.\n2.Pipoca is 9 years old.\n3.Tamara is 4 years older than the animal Mika works with.\n4.The tamarin Nia works with is younger than Zephyr.\n5.Of the tamarin Bella works with and the 14-year-old, one is Pipoca and the other is Tamara.\n6.The 14-year-old is cared for by Clara.\n\nSolve the grid puzzle by filling the table:\n+--------+--------------+------------+\n|   Ages | Tamarins     | Caretakers |\n+========+==============+============+\n|      5 |              |            |\n+--------+--------------+------------+\n|      7 |              |            |\n+--------+++-------------+------------+\n|      9 |              |            |\n+--------+--------------+------------+\n|     12 |              |            |\n+--------+--------------+------------+\n|     14 |              |            |\n+--------+--------------+------------+\n\nUse the clues to fill the table with the following categories:\nTamarins: Bella, Nia, Mika, Pipoca, Tamara\nCaretakers: Lila, Zephyr, Dora, Eva, Clara'